Gemfile.lock
SRCH-151 - Upgrade loofah to version 2.2.3
=> SRCH-151 - Upgrade loofah to version 2.2.3

Gemfile.lock
[SRCH-198] - Security vulnerability ffi
=> Release 1.0.2

Gemfile.lock
[SRCH-210] - update rack to address security vulnerability
=> Release 1.0.3

Gemfile, Gemfile.lock, app/queries/album_detection.rb, app/queries/top_hits.rb, app/workers/flickr_photos_importer.rb, app/workers/mrss_photos_importer.rb
This PR contains several changes designed to make Asis forward compatible with Elasticsearch 6.8.
=> Elasticsearch 6.8 compatibility

.circleci/config.yml, app/models/concerns/aliased_index.rb, spec/workers/flickr_photos_importer_spec.rb, spec/workers/mrss_photos_importer_spec.rb
[SRCH-1241] - run specs against Elasticsearch 6.8
=> Release 1.1.7

Gemfile.lock
[SRCH-1315] - Bump nokogiri and puma gems
=> Release 1.1.8

config/elasticsearch.yml, config/initializers/elasticsearch.rb
SRCH-1837 add Elasticsearch client logging to Rails log (#73)
=> Release 1.1.12

.circleci/config.yml, Gemfile.lock
SRCH-2404 use bundler 2.2.24
- use ruby orb to install gems on CircleCi
=> SRCH-2404 use bundler 2.2.24

.circleci/config.yml, Gemfile.lock
SRCH-2404 use bundler 2.2.24 (#99) 
- use ruby orb to install gems on CircleCi
=> Release 1.1.19

lib/elastic_settings.rb
- Resolves the standard token filter deprecation warning logged in `es6-docker-cluster_deprecation.log`
- Per https://www.elastic.co/guide/en/elasticsearch/reference/6.8/analysis-standard-tokenfilter.html the standard token filter has not done anything since its deprecation in ElasticSearch 6.5.
Existing tests pass; logged deprecation removed.
Will not be manually tested.
=> SRCH-1830 Remove standard token filter

lib/elastic_settings.rb
- SRCH-1830 Remove standard token filter (#121)
Existing tests pass; logged deprecation removed.
Team determined that manual testing was not needed
=> Release - SRCH-1830

Gemfile.lock
- Upgrades to bundler 2.3.8
- Repo uses most recent CircleCI Ruby Orb so no further action needed there
N/A
N/A
=> SRCH-2864 Upgrade to bundler 2.3.8

Gemfile.lock
- SRCH-2864 Upgrade to bundler 2.3.8
=> Release - SRCH-2864 

app/queries/top_hits.rb
- SRCH-1829 specify minimum_should_match (#127)
=> Release - SRCH-1829

Gemfile.lock, app/models/album_detector.rb, spec/models/album_detection_photo_iterator_spec.rb, spec/models/album_detector_spec.rb
- SRCH-1840 remove code anticipating version conflicts
=> Release - SRCH-1840

.github/pull_request_template.md
- Renaming 'master' branch to 'main': text in .github/pull_request_template.md.
=> SRCH-3009: Update Asis to use Main

.codeinventory.yml, .github/pull_request_template.md, Gemfile.lock
Functional
- [SRCH-3106 Bump rack from 2.2.3 to 2.2.3.1](https://github.com/GSA/asis/commit/83a2f47bbcfd6196c6a5f5554888c141475b06a3)
Housekeeping
- [SRCH-3070 Update Email in Code Inventory](https://github.com/GSA/asis/commit/1d79ad11ed7b3cc0660ebc31d0c0e2d46cb93897)
- [SRCH-3009: Update Asis to use Main](https://github.com/GSA/asis/commit/c8eebd1fb4960ead6e5cdc286ed4c9dea871dcbd)
No functional changes
No manual testing
=> Release - SRCH-3106

.circleci/config.yml
- Update Redis to 6.2 which is a latest supported version in CircleCI config
=> SRCH-3266 update CircleCI config to Redis 6.2

.circleci/config.yml, .github/pull_request_template.md
- [SRCH-3266 update CircleCI config to Redis 6.2](https://github.com/GSA/asis/commit/0703527ae749bf55ae79ddf8be2f89a6bd44ae83)
- [SRCH-3460 Remove bundle update from PR template](https://github.com/GSA/asis/commit/593585eb548a1c87fb25ea22ba8b324cf6beaad7)
=> Release - SRCH-3266, SRCH-3460

.circleci/config.yml
This PR bumps the versions of Ruby tested in CircleCI.
=> SRCH-3909 test against Ruby 3.0.5

Gemfile.lock
This PR upgrades bundler to the latest version.
=> SRCH-3839 Upgrade bundler in asis

.circleci/config.yml, Gemfile.lock
- SRCH-3909 test against Ruby 3.0.5
- SRCH-3839 Upgrade bundler in asis
=> Release - SRCH-3909, SRCH-3839

config/initializers/filter_parameter_logging.rb, spec/config/initializers/filter_parameter_logging_spec.rb
- Adds `query` to `filtered_parameter_logging` to ensure potentially sensitive queries do not end up in our asis logs. 
=> SRCH-3934 Filter query from request params in logs

config/initializers/filter_parameter_logging.rb, spec/config/initializers/filter_parameter_logging_spec.rb
- SRCH-3934 Filter query from request params in logs 
=> Release - SRCH-3934

.dockerignore, .env/development/app, Dockerfile, config/application.rb, config/environments/test.rb, config/initializers/redis.rb, config/initializers/sidekiq.rb, config/sidekiq.yml
- Add a Dockerfile and the configuration to the ASIS.
- ASIS service will be created and run using docker-compose.yml in search-services. Refer to https://github.com/GSA/search-services/pull/10
=> SRCH-4121 Dockerize ASIS development

README.md
- Updated ReadMe for using ASIS within docker.
=> SRCH-4122 Update ASIS README about using docker

.dockerignore, .env/development/app, Dockerfile, config/application.rb, config/environments/test.rb, config/initializers/redis.rb, config/initializers/sidekiq.rb, config/sidekiq.yml
- SRCH-4121 Dockerize ASIS development
-
=> Release - SRCH-4121 Dockerize ASIS development 

config/initializers/redis.rb, config/initializers/sidekiq.rb, config/sidekiq.yml
- rename `redis_url` to `url` to match with usasearch-cookbooks.
=> SRCH-4282 Rename - ASIS redis_url to url

config/initializers/redis.rb, config/initializers/sidekiq.rb, config/sidekiq.yml
- SRCH-4282 Rename - ASIS redis_url to url
=> Release - SRCH-4282 Rename - ASIS redis_url to url 

config/initializers/elasticsearch.rb
SRCH-4303 Enable TLS for Elasticsearch connections
=> SRCH-4303 Enable TLS for Elasticsearch connections

config/initializers/elasticsearch.rb
- [SRCH-4303 Enable TLS for Elasticsearch connections](https://github.com/GSA/asis/commit/88f442e5fb36dd2e4c60014855b55ff0b1f8af60)
=> Release - SRCH-4303

config/environments/production.rb
- SRCH-4511 Force SSL in production
=> Release SRCH-4511

config/application.rb
- This PR does a couple of small cleanup items for the Rails 7.0 upgrade based on the requirements of the following two tickets: 
* [SRCH-4370](https://cm-jira.usa.gov/browse/SRCH-4370)
* [SRCH-4373](https://cm-jira.usa.gov/browse/SRCH-4373)
=> SRCH-4370 & SRCH-4373: Post Rails upgrade items. Cleanup.

.gitignore, Dockerfile, Dockerfile.dev, bin/secure_docker, config/elasticsearch.yml, config/flickr.yml, config/newrelic.yml, config/secrets.yml, config/sidekiq.yml
- SRCH-4959: Add new production Dockerfile.
=> Release - SRCH-4959 & SRCH-5034: Add new production Dockerfile.

config/elasticsearch.yml, config/flickr.yml, config/initializers/elasticsearch.rb, config/newrelic.yml, config/sidekiq.yml
- This PR adds staging environment to config files based on requirements from this ticket: https://cm-jira.usa.gov/browse/SRCH-5084
=> SRCH-5084: Add staging environment to yaml config files.

config/environments/production.rb
=> SRCH-5217 Set production log level configurable through the environment

bin/secure_docker, config/environments/production.rb, config/initializers/redis.rb, config/initializers/sidekiq.rb
=> SRCH-5217 SRCH-5168 Fix  error `visit_Psych_Nodes_Alias' ... (Psych::BadAlias)`.  Fix suid & sgid deletion, remove crontabs and init files

Dockerfile
=> SRCH-5243 Setup logs to use STOUT and do not install development gems

Gemfile, Gemfile.lock, config/application.rb, config/environments/production.rb
=> SRCH-5293 Setup semantic logger

config/routes.rb
Sidekiq ui will be handled by searchgov. See https://github.com/GSA/search-gov/pull/1600.
=> SRCH-5255 Remove sidekiq ui

appspec.yml, buildspec_asis.yml, cicd-scripts/fetch_env_vars.sh
- config files for code deploy and code build*
- [ x] You have merged the latest changes from the target branch (usually `main`) into your branch.
- [ x] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.
- [ x] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
=> SRCH-5391-codepipeline

.env/development/app, .gitignore, Capfile, Gemfile, Gemfile.lock, appspec.yml, buildspec_asis.yml, cicd-scripts/fetch_env_vars.sh, config/application.rb, config/deploy.rb, config/deploy/production.rb, config/deploy/staging.rb, config/elasticsearch.yml, config/environments/production.rb, config/initializers/redis.rb, config/initializers/sidekiq.rb, config/schedule.rb, config/sidekiq.yml
- This PR syncs main to staging
=> Sync Staging and Main

buildspec_asis.yml
- Add CRON_SERVER_ADDRESSES to buildspec
=>  SRCH-5561 Add CRON_SERVER_ADDRESSES to buildspec

Capfile, config/deploy.rb, config/deploy/staging.rb, config/sidekiq.yml
=> SRCH-5393 Setup sidekiq workers through capistrano

buildspec_asis.yml
- Make sure to install sidekiq service before deploy
=> SRCH-5393 Make sure to install sidekiq service before deploy

config/environments/production.rb
- This PR adds the following host to production environment: `asis.search.usa.gov`
=> Add Production Host URL

config/environments/production.rb
=> Add Production Host URL (#289)

config/environments/production.rb
- This PR adds a different operator to the host config.
=> Change operator to host domains

config/environments/production.rb
=> Sync branches Staging > main  (#294)

config/newrelic.yml
=> SRCH-5619 setup newrelic

config/newrelic.yml
- Match newrelic production name
=> SRCH-5619 Fix newrelic app name to match production

config/deploy.rb
- Setup puma to use ASIS_THREADS and ASIS_WORKERS
=> SRCH-5617 parameterize puma settings

buildspec_asis.yml
- Add params for threads in buildspec
=> SRCH-5617 Add paras to buildspec

buildspec_asis.yml
* Add params to buildspec.
* Add experted vars.
---------
=> SRCH-5617 Add paras to buildspec (#301)

buildspec_asis.yml, config/newrelic.yml
- SRCH-5619 setup newrelic
- SRCH-5617 parameterize puma settings
- SRCH-5617 Add params to buildspec 
=> Production release SRCH-5619 SRCH-5617 SRCH-5617

config/elasticsearch.yml
- Update log_level with env variable in elasticsearch_client.yml.
=> SRCH-5733 Update ES log_level with env variable for ASIS

config/deploy/development.rb
- Create capistrano deploy/development file
- Setup main branch to be use by the development environment
=> SRCH-5805 Create Capistrano deploy/development file

Gemfile, Gemfile.lock
- Lock version of capistrano-sidekiq and capistrano3-puma to fix deployment
- [] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
=> SRCH-5810 Lock version of capistrano-sidekiq and capistrano3-puma
