Gemfile.lock

SRCH-800 - upgrade Nokogiri gem due to security vulnerability with Nokogiri gem. See
https://nvd.nist.gov/vuln/detail/CVE-2019-5477 for more details

SRCH-800- upgrade Nokogiri gem due to security vulnerability

---

.circleci/config.yml

This PR:
- removes ruby 2.3 from the test matrix on CirclCi. Tests will be run against ruby 2.5 and 2.6.
- names the test jobs

SRCH-811 remove ruby 2.3 from test matrix

---

.circleci/config.yml
Gemfile.lock

[SRCH-808] - upgrade Nokogiri gem due to security vulnerability
[SRCH-811] - remove ruby 2.3 from test matrix

Release 1.1.4

---

app/queries/album_detection.rb
app/queries/top_hits.rb
app/workers/flickr_photos_importer.rb
app/workers/mrss_photos_importer.rb

This PR updates the FlickrPhotosImporter and a couple of other scripts to use the Painless instead of Groovy scripting language, which has been deprecated. This should also resolve production failures due to the use of Groovy scripts, which are disabled in production.

SRCH-1204 SRCH-1206 update importers to use Painless scripting

---

.circleci/config.yml
app/models/concerns/aliased_index.rb
spec/workers/flickr_photos_importer_spec.rb
spec/workers/mrss_photos_importer_spec.rb

This PR adds Elasticsearch 6.8 and Ruby 2.7 to the test matrix. ES 5.6 will remain the default in specs until we have upgraded to 6.8.

SRCH-1241 run specs against Elasticsearch 6.8

---

.circleci/config.yml
.docker/bin/elasticsearch-docker
.docker/config/elasticsearch.yml
README.md
config/mrss_profiles.csv
docker-compose.yml

This PR:
- updates the CircleCI config to use ES 6.8 by default
- updates the README to include instructions on running Elasticsearch locally using Docker

SRCH-1252 update development/CircleCI to use Elasticsearch 6.8

---

config/elasticsearch.yml
config/initializers/elasticsearch.rb

@MyNameIsMissing , this is a simple change to allow the Elasticsearch client in ASIS to write logging information to the Rails log, making it easier for devs to see what's going on in ES for any given Rails activity. There will be a corresponding PR in the cookbooks to update the ES config for ASIS. If you aren't comfortable reviewing, feel free to reassign to @jmax-fearless .

SRCH-1837 add Elasticsearch client logging to Rails log

---

.circleci/config.yml

Removed all traces Ruby 2.5. Also switched parameters to matrix
syntax, and removed defaults for all parameters, since the matrix
should handle all values, and we _want_ it to blow up if that's not
happening.

SRCH-2219 - Remove Ruby 2.5 from ASIS CircleCI

---

Gemfile.lock

This is a follow-up to https://github.com/GSA/asis/pull/94. That PR included the `Gemfile.lock` updates as a result of `bundle update`, but it did *not* include the `Gemfile.lock` updates as a result of bumping `puma`. This PR rights that wrong.

SRCH-2317 bump puma

---

Gemfile.lock

This is a follow-up to #94. That PR included the Gemfile.lock updates as a result of bundle update, but it did not include the Gemfile.lock updates as a result of bumping puma. This PR rights that wrong.

Release 1.1.18

---

.circleci/config.yml

SRCH-2639 remove Ruby 2.6 from CircleCi matrix
- use Ruby orb 1.4.0

SRCH-2639 remove Ruby 2.6 from CircleCi matrix

---

app/queries/top_hits.rb

This PR resolves the following breaking change in Elasticsearch 7.x:
https://www.elastic.co/guide/en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_the_filter_context_has_been_removed
This change preserves the 6.x behavior by explicitly setting `minimum_should_match: 1`, which ES 7.x will no longer do automatically.

SRCH-1829 specify minimum_should_match

---

.codeclimate.yml
spec/models/flickr_album_detector_spec.rb
spec/models/mrss_album_detector_spec.rb

This PR updates the album detector specs to ensure that the specs will pass on both Elasticsearch 6 & 7. This change papers over a change in functionality between ES 6 & 7, which is that an encoded `+` in a document id in a URL is converted to a space in ES 6, but is indexed as a `+` in ES 7. Per discussion in the ticket, we're not planning to make code changes to prepare for the change, as a very small number of documents would be affected.
I've also disabled Code Climate's `duplication` engine for specs. (This is in line with our configuration in search-gov. There's value to de-duping specs, but it can also slow down development and reduce spec readability. So we leave spec de-duping to the discretion of the developer.)
Please ensure you have addressed all concerns below before marking …

SRCH-1841 remove spaces from image ids in specs

---

.circleci/config.yml
spec/models/album_detector_spec.rb

This PR updates our CircleCi configuration. It:
- adds Elasticsearch 7.17.3 to the test matrix
- bumps the ruby orb version
- refactors the configuration to use the `ruby/rspec-test` command from the orb

SRCH-1827 run specs against Elasticsearch 6 & 7 in CircleCi

---

app/models/concerns/aliased_index.rb
spec/models/image_search_spec.rb
spec/rails_helper.rb

This is a follow-up to https://github.com/GSA/asis/pull/141. That fix masked a Heisenbug; the process of my poking around and verifying that my "fix" did the trick had the same effect as a `sleep`. To avoid actually adding a several-second `sleep` in the specs (in order to let ES's caching catch up), I've recreated the indices before that particular spec and added some comments to guide future devs.

SRCH-2987 prevent ImageSearch spec from failing intermittently

---

.github/pull_request_template.md

- removing squash requirement from PR template
:warning: You have run `bundle update` and committed your changes to Gemfile.lock.

SRCH-3298 remove squash requirement from PR template

---

.circleci/config.yml
README.md

This PR removes ElasticSearch 6.x from the CI matrix.

SRCH-1825 Make ElasticSearch 7.x the default for development and testing

---

config/initializers/elasticsearch.rb

This PR disables the `reload_on_connections` and `reload_on_failure` Elasticsearch client options in order to address an issue with ES connections in production.

SRCH-4593 Disable Elasticsearch discovery

---

config/initializers/elasticsearch.rb

- This PR reverts changes the environment variable in the ElasticSearch initializer based on this ticket: https://cm-jira.usa.gov/browse/SRCH-5092

SRCH-5092: Revert changes to environment variable in elasticsearch.

---

config/deploy.rb

- Remove hardcoded ruby version from deploy.rb. Capistrano will pick up the default version from .ruby-version

SRCH-5549 Remove hardcoded ruby version from deploy.rb
